/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "supabase.index/project.Project"
      "user": string
    }
    "HelpEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "PlacesApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseDatabasePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "site": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}