name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  DeployApp:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::075245960512:role/GitHub
          aws-region: af-south-1

      - name: Install dependencies
        run: npm ci

       - name: Set SST secrets
        run: |
          npx sst secret set PlacesApiKey ${{ secrets.PLACES_API_KEY }}

      - name: Deploy app
        run: |
          npx sst deploy --stage production
